package deliveroo.it.restourantsprint.controllers;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.http.ResponseEntity;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;

import org.springframework.web.bind.annotation.RestController;

import deliveroo.it.restourantsprint.repositories.FoodRepository;

@RestController
@RequestMapping(path = "/deliveroo") // This means URL's start with /demo (after Application path)
public class Menu {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FoodRepository foodRepository;

    // @GetMapping("/menu")
    // public Iterable<Dish> getAll() {
    //     // This returns a JSON or XML with the users
    //     return menuRepository.findAll();
    // }

    // @GetMapping("/menu/{id}")
    // Optional<Dish> getMenu(@PathVariable Integer id) {
        
    //     return menuRepository.findById(id);
    // }

}